### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by rando128** [maneuver-agency/iubenda-nuxt-module#1]
Does this module support SSR? I can't manage to get it to work for showing the CS preference when clicking on links with the .iubenda-cs-preferences-link class

**Comment by davidmaneuver** [comment]
Hi @rando128, I'm sorry I couldn't find the time to get to you earlier.

I'm not sure about the .iubenda-cs-preferences-link classes. I haven't used them yet in combination with this module. I try to look into it soon.

Did you, by any chance, found a workaround that you like to share?

**Comment by rando128** [comment]
No workaround unfortunately, except implementing it natively without using this module :(

**Comment by davidmaneuver** [comment]
@rando128 I've just tested this and it works out of the box.

Can you perhaps show me your implementation? (config, vue component, ...)
