### ISSUE TITLE
Script in multiple languages

### ISSUE THREAD

**Issue by vervelover** [maneuver-agency/iubenda-nuxt-module#2]
Hi,

thank you for developing this plugin, I have a question: how do I load different banners according to the selected language? the cookie policy id changes for each language even if the site id is the same, I couldn't figure out a way to do this with your plugin,

Thank you
Alessio

**Comment by davidmaneuver** [comment]
Hello @vervelover,

Thanks for reaching out. As a matter of fact, we are just experiencing the same problem. We need to adjust the script based on the active locale, using the nuxt/i18n module.

In the coming weeks we will look for a solution. I'll keep you posted.

**Comment by devilmark84** [comment]
Any news?

**Comment by davidmaneuver** [comment]
Hi,
Turns out this is more difficult than we anticipated due to the fixed script being inserted.
We just released a new version where the PageEmbed component integrates with the current locale.

We are now focussing on a Nuxt3 version.

**Comment by vernaillen** [comment]
hi @davidmaneuver 
Any news on i18n support and the Nuxt 3 version?   I'm open to collaborate

**Comment by davidmaneuver** [comment]
Hi @vernaillen.
As we are most likely discontinuing our Nuxt development, we won't be upgrading this module to support Nuxt 3.
Feel free to create a PR if you want, I'd be happy to merge.
